services:
  browser:
    build: .
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./browser
        target: /home/local/
    stdin_open: true
    tty: true
    networks:
      - net
    ports:
      - 8000:8000

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./server
        target: /home/local/
    stdin_open: true
    tty: true
    networks:
      - net
    ports:
      - 8080:8080

networks:
  net:
    driver: bridge
